spring:
  application:
    name: tea-java

  datasource:
    url: jdbc:mysql://localhost:3306/tea?serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 基本配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 60000
      # 检测间隔时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
  data:
    redis:
      timeout: 0
      database: 0  # Redis数据库索引（默认为0）
      host: 127.0.0.1  # Redis服务器地址
      port: 6378  # Redis服务器连接端口
      password: "123"  # Redis服务器连接密码（默认为空）
      jedis:
        pool:
          max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 8  # 连接池中的最大空闲连接
          min-idle: 0  # 连接池中的最小空闲连接
  mail:
    host: smtp.qq.com
    port: 587  # 或465
    username: 2776274226@qq.com  # 你的QQ邮箱
    password: uwcukoiprfgeddag  # QQ邮箱授权码（不是QQ密码）
    properties:
      mail:
        sendName: 茶偶
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory  # 使用SSL
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8