services:
  mysql:
    image: mysql:latest
    container_name: tea_1
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=123
    restart: always
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: tea_redis_1
    ports:
      - "6378:6379"
    command: redis-server --requirepass 123
    restart: always

  minio:
    image: minio/minio
    container_name: tea_minio_1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server /data --console-address ":9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin 12345678;
      /usr/bin/mc mb myminio/paper;
      /usr/bin/mc mb myminio/attachment;
      /usr/bin/mc mb myminio/temp;
      /usr/bin/mc mb myminio/reporter;
      /usr/bin/mc anonymous set public myminio/paper;
      /usr/bin/mc anonymous set public myminio/attachment;
      /usr/bin/mc anonymous set public myminio/temp;
      /usr/bin/mc anonymous set public myminio/reporter;
      exit 0;
      "
